locals {
  origin = {
    x = tonumber(split(",", var.origin)[0])
    y = tonumber(split(",", var.origin)[1])
    z = tonumber(split(",", var.origin)[2])
  }

  coordinates = [
    # front
    "${local.origin.x + 0};${local.origin.y - 2};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 1};${local.origin.y - 2};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 2};${local.origin.y - 2};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 3};${local.origin.y - 2};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 4};${local.origin.y - 2};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 2};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y - 1};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 1};${local.origin.y - 1};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 2};${local.origin.y - 1};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 3};${local.origin.y - 1};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 4};${local.origin.y - 1};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 1};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 0};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 1};${local.origin.y + 0};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 4};${local.origin.y + 0};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 0};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 1};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 1};${local.origin.y + 1};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 4};${local.origin.y + 1};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 1};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 2};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 1};${local.origin.y + 2};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 2};${local.origin.y + 2};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 3};${local.origin.y + 2};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 4};${local.origin.y + 2};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 2};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 1};${local.origin.y + 3};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 2};${local.origin.y + 3};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 3};${local.origin.y + 3};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 4};${local.origin.y + 3};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 2};${local.origin.y + 4};${local.origin.z + 0};minecraft:stone",
    "${local.origin.x + 3};${local.origin.y + 4};${local.origin.z + 0};minecraft:stone",

    # back
    "${local.origin.x + 0};${local.origin.y - 2};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 1};${local.origin.y - 2};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 2};${local.origin.y - 2};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 3};${local.origin.y - 2};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 4};${local.origin.y - 2};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 2};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y - 1};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 1};${local.origin.y - 1};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 2};${local.origin.y - 1};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 3};${local.origin.y - 1};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 4};${local.origin.y - 1};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 1};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 0};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 1};${local.origin.y + 0};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 2};${local.origin.y + 0};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 3};${local.origin.y + 0};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 4};${local.origin.y + 0};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 0};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 1};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 1};${local.origin.y + 1};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 4};${local.origin.y + 1};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 1};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 2};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 1};${local.origin.y + 2};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 4};${local.origin.y + 2};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 2};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 1};${local.origin.y + 3};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 2};${local.origin.y + 3};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 3};${local.origin.y + 3};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 4};${local.origin.y + 3};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 2};${local.origin.y + 4};${local.origin.z + 6};minecraft:stone",
    "${local.origin.x + 3};${local.origin.y + 4};${local.origin.z + 6};minecraft:stone",

    # sides
    "${local.origin.x + 0};${local.origin.y - 1};${local.origin.z + 1};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y - 1};${local.origin.z + 2};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y - 1};${local.origin.z + 3};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y - 1};${local.origin.z + 4};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y - 1};${local.origin.z + 5};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y - 2};${local.origin.z + 1};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y - 2};${local.origin.z + 2};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y - 2};${local.origin.z + 3};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y - 2};${local.origin.z + 4};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y - 2};${local.origin.z + 5};minecraft:stone",

    "${local.origin.x + 5};${local.origin.y - 1};${local.origin.z + 1};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 1};${local.origin.z + 2};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 1};${local.origin.z + 3};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 1};${local.origin.z + 4};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 1};${local.origin.z + 5};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 2};${local.origin.z + 1};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 2};${local.origin.z + 2};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 2};${local.origin.z + 3};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 2};${local.origin.z + 4};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y - 2};${local.origin.z + 5};minecraft:stone",

    "${local.origin.x + 0};${local.origin.y + 0};${local.origin.z + 1};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 0};${local.origin.z + 2};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 0};${local.origin.z + 3};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 0};${local.origin.z + 4};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 0};${local.origin.z + 5};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 1};${local.origin.z + 1};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 1};${local.origin.z + 2};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 1};${local.origin.z + 3};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 1};${local.origin.z + 4};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 1};${local.origin.z + 5};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 2};${local.origin.z + 1};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 2};${local.origin.z + 2};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 2};${local.origin.z + 3};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 2};${local.origin.z + 4};minecraft:stone",
    "${local.origin.x + 0};${local.origin.y + 2};${local.origin.z + 5};minecraft:stone",

    "${local.origin.x + 5};${local.origin.y + 0};${local.origin.z + 1};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 0};${local.origin.z + 2};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 0};${local.origin.z + 3};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 0};${local.origin.z + 4};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 0};${local.origin.z + 5};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 1};${local.origin.z + 1};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 1};${local.origin.z + 2};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 1};${local.origin.z + 3};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 1};${local.origin.z + 4};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 1};${local.origin.z + 5};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 2};${local.origin.z + 1};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 2};${local.origin.z + 2};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 2};${local.origin.z + 3};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 2};${local.origin.z + 4};minecraft:stone",
    "${local.origin.x + 5};${local.origin.y + 2};${local.origin.z + 5};minecraft:stone",

    # roof
    "${local.origin.x - 1};${local.origin.y + 2};${local.origin.z - 1};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x - 1};${local.origin.y + 2};${local.origin.z + 0};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x - 1};${local.origin.y + 2};${local.origin.z + 1};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x - 1};${local.origin.y + 2};${local.origin.z + 2};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x - 1};${local.origin.y + 2};${local.origin.z + 3};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x - 1};${local.origin.y + 2};${local.origin.z + 4};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x - 1};${local.origin.y + 2};${local.origin.z + 5};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x - 1};${local.origin.y + 2};${local.origin.z + 6};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x - 1};${local.origin.y + 2};${local.origin.z + 7};minecraft:acacia_stairs[facing=east]",

    "${local.origin.x + 0};${local.origin.y + 3};${local.origin.z - 1};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 0};${local.origin.y + 3};${local.origin.z + 0};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 0};${local.origin.y + 3};${local.origin.z + 1};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 0};${local.origin.y + 3};${local.origin.z + 2};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 0};${local.origin.y + 3};${local.origin.z + 3};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 0};${local.origin.y + 3};${local.origin.z + 4};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 0};${local.origin.y + 3};${local.origin.z + 5};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 0};${local.origin.y + 3};${local.origin.z + 6};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 0};${local.origin.y + 3};${local.origin.z + 7};minecraft:acacia_stairs[facing=east]",

    "${local.origin.x + 1};${local.origin.y + 4};${local.origin.z - 1};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 1};${local.origin.y + 4};${local.origin.z + 0};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 1};${local.origin.y + 4};${local.origin.z + 1};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 1};${local.origin.y + 4};${local.origin.z + 2};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 1};${local.origin.y + 4};${local.origin.z + 3};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 1};${local.origin.y + 4};${local.origin.z + 4};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 1};${local.origin.y + 4};${local.origin.z + 5};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 1};${local.origin.y + 4};${local.origin.z + 6};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 1};${local.origin.y + 4};${local.origin.z + 7};minecraft:acacia_stairs[facing=east]",

    "${local.origin.x + 2};${local.origin.y + 5};${local.origin.z - 1};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 2};${local.origin.y + 5};${local.origin.z + 0};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 2};${local.origin.y + 5};${local.origin.z + 1};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 2};${local.origin.y + 5};${local.origin.z + 2};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 2};${local.origin.y + 5};${local.origin.z + 3};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 2};${local.origin.y + 5};${local.origin.z + 4};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 2};${local.origin.y + 5};${local.origin.z + 5};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 2};${local.origin.y + 5};${local.origin.z + 6};minecraft:acacia_stairs[facing=east]",
    "${local.origin.x + 2};${local.origin.y + 5};${local.origin.z + 7};minecraft:acacia_stairs[facing=east]",

    "${local.origin.x + 3};${local.origin.y + 5};${local.origin.z - 1};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 3};${local.origin.y + 5};${local.origin.z + 0};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 3};${local.origin.y + 5};${local.origin.z + 1};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 3};${local.origin.y + 5};${local.origin.z + 2};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 3};${local.origin.y + 5};${local.origin.z + 3};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 3};${local.origin.y + 5};${local.origin.z + 4};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 3};${local.origin.y + 5};${local.origin.z + 5};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 3};${local.origin.y + 5};${local.origin.z + 6};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 3};${local.origin.y + 5};${local.origin.z + 7};minecraft:acacia_stairs[facing=west]",

    "${local.origin.x + 4};${local.origin.y + 4};${local.origin.z - 1};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 4};${local.origin.y + 4};${local.origin.z + 0};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 4};${local.origin.y + 4};${local.origin.z + 1};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 4};${local.origin.y + 4};${local.origin.z + 2};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 4};${local.origin.y + 4};${local.origin.z + 3};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 4};${local.origin.y + 4};${local.origin.z + 4};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 4};${local.origin.y + 4};${local.origin.z + 5};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 4};${local.origin.y + 4};${local.origin.z + 6};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 4};${local.origin.y + 4};${local.origin.z + 7};minecraft:acacia_stairs[facing=west]",

    "${local.origin.x + 5};${local.origin.y + 3};${local.origin.z - 1};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 5};${local.origin.y + 3};${local.origin.z + 0};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 5};${local.origin.y + 3};${local.origin.z + 1};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 5};${local.origin.y + 3};${local.origin.z + 2};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 5};${local.origin.y + 3};${local.origin.z + 3};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 5};${local.origin.y + 3};${local.origin.z + 4};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 5};${local.origin.y + 3};${local.origin.z + 5};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 5};${local.origin.y + 3};${local.origin.z + 6};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 5};${local.origin.y + 3};${local.origin.z + 7};minecraft:acacia_stairs[facing=west]",

    "${local.origin.x + 6};${local.origin.y + 2};${local.origin.z - 1};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 6};${local.origin.y + 2};${local.origin.z + 0};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 6};${local.origin.y + 2};${local.origin.z + 1};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 6};${local.origin.y + 2};${local.origin.z + 2};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 6};${local.origin.y + 2};${local.origin.z + 3};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 6};${local.origin.y + 2};${local.origin.z + 4};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 6};${local.origin.y + 2};${local.origin.z + 5};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 6};${local.origin.y + 2};${local.origin.z + 6};minecraft:acacia_stairs[facing=west]",
    "${local.origin.x + 6};${local.origin.y + 2};${local.origin.z + 7};minecraft:acacia_stairs[facing=west]",

    # upside down roof
    "${local.origin.x + 0};${local.origin.y + 2};${local.origin.z - 1};minecraft:acacia_stairs[facing=west, half=top]",
    "${local.origin.x + 1};${local.origin.y + 3};${local.origin.z - 1};minecraft:acacia_stairs[facing=west, half=top]",
    "${local.origin.x + 2};${local.origin.y + 4};${local.origin.z - 1};minecraft:acacia_stairs[facing=west, half=top]",
    "${local.origin.x + 3};${local.origin.y + 4};${local.origin.z - 1};minecraft:acacia_stairs[facing=east, half=top]",
    "${local.origin.x + 4};${local.origin.y + 3};${local.origin.z - 1};minecraft:acacia_stairs[facing=east, half=top]",
    "${local.origin.x + 5};${local.origin.y + 2};${local.origin.z - 1};minecraft:acacia_stairs[facing=east, half=top]",
    "${local.origin.x + 0};${local.origin.y + 2};${local.origin.z + 7};minecraft:acacia_stairs[facing=west, half=top]",
    "${local.origin.x + 1};${local.origin.y + 3};${local.origin.z + 7};minecraft:acacia_stairs[facing=west, half=top]",
    "${local.origin.x + 2};${local.origin.y + 4};${local.origin.z + 7};minecraft:acacia_stairs[facing=west, half=top]",
    "${local.origin.x + 3};${local.origin.y + 4};${local.origin.z + 7};minecraft:acacia_stairs[facing=east, half=top]",
    "${local.origin.x + 4};${local.origin.y + 3};${local.origin.z + 7};minecraft:acacia_stairs[facing=east, half=top]",
    "${local.origin.x + 5};${local.origin.y + 2};${local.origin.z + 7};minecraft:acacia_stairs[facing=east, half=top]",

    # glass window
    "${local.origin.x + 2};${local.origin.y + 1};${local.origin.z + 6};minecraft:glass_pane",
    "${local.origin.x + 2};${local.origin.y + 2};${local.origin.z + 6};minecraft:glass_pane",
    "${local.origin.x + 3};${local.origin.y + 1};${local.origin.z + 6};minecraft:glass_pane",
    "${local.origin.x + 3};${local.origin.y + 2};${local.origin.z + 6};minecraft:glass_pane",

    # floor
    "${local.origin.x + 1};${local.origin.y - 1};${local.origin.z + 1};minecraft:glass",
    "${local.origin.x + 1};${local.origin.y - 1};${local.origin.z + 2};minecraft:glass",
    "${local.origin.x + 1};${local.origin.y - 1};${local.origin.z + 3};minecraft:glass",
    "${local.origin.x + 1};${local.origin.y - 1};${local.origin.z + 4};minecraft:glass",
    "${local.origin.x + 1};${local.origin.y - 1};${local.origin.z + 5};minecraft:glass",

    "${local.origin.x + 2};${local.origin.y - 1};${local.origin.z + 1};minecraft:glass",
    "${local.origin.x + 2};${local.origin.y - 1};${local.origin.z + 2};minecraft:glass",
    "${local.origin.x + 2};${local.origin.y - 1};${local.origin.z + 3};minecraft:glass",
    "${local.origin.x + 2};${local.origin.y - 1};${local.origin.z + 4};minecraft:glass",
    "${local.origin.x + 2};${local.origin.y - 1};${local.origin.z + 5};minecraft:glass",

    "${local.origin.x + 3};${local.origin.y - 1};${local.origin.z + 1};minecraft:glass",
    "${local.origin.x + 3};${local.origin.y - 1};${local.origin.z + 2};minecraft:glass",
    "${local.origin.x + 3};${local.origin.y - 1};${local.origin.z + 3};minecraft:glass",
    "${local.origin.x + 3};${local.origin.y - 1};${local.origin.z + 4};minecraft:glass",
    "${local.origin.x + 3};${local.origin.y - 1};${local.origin.z + 5};minecraft:glass",

    "${local.origin.x + 4};${local.origin.y - 1};${local.origin.z + 1};minecraft:glass",
    "${local.origin.x + 4};${local.origin.y - 1};${local.origin.z + 2};minecraft:glass",
    "${local.origin.x + 4};${local.origin.y - 1};${local.origin.z + 3};minecraft:glass",
    "${local.origin.x + 4};${local.origin.y - 1};${local.origin.z + 4};minecraft:glass",
    "${local.origin.x + 4};${local.origin.y - 1};${local.origin.z + 5};minecraft:glass",

    # air under floor
    "${local.origin.x + 1};${local.origin.y - 2};${local.origin.z + 1};minecraft:air",
    "${local.origin.x + 1};${local.origin.y - 2};${local.origin.z + 2};minecraft:air",
    "${local.origin.x + 1};${local.origin.y - 2};${local.origin.z + 3};minecraft:air",
    "${local.origin.x + 1};${local.origin.y - 2};${local.origin.z + 4};minecraft:air",
    "${local.origin.x + 1};${local.origin.y - 2};${local.origin.z + 5};minecraft:air",

    "${local.origin.x + 2};${local.origin.y - 2};${local.origin.z + 1};minecraft:air",
    "${local.origin.x + 2};${local.origin.y - 2};${local.origin.z + 2};minecraft:air",
    "${local.origin.x + 2};${local.origin.y - 2};${local.origin.z + 3};minecraft:air",
    "${local.origin.x + 2};${local.origin.y - 2};${local.origin.z + 4};minecraft:air",
    "${local.origin.x + 2};${local.origin.y - 2};${local.origin.z + 5};minecraft:air",

    "${local.origin.x + 3};${local.origin.y - 2};${local.origin.z + 1};minecraft:air",
    "${local.origin.x + 3};${local.origin.y - 2};${local.origin.z + 2};minecraft:air",
    "${local.origin.x + 3};${local.origin.y - 2};${local.origin.z + 3};minecraft:air",
    "${local.origin.x + 3};${local.origin.y - 2};${local.origin.z + 4};minecraft:air",
    "${local.origin.x + 3};${local.origin.y - 2};${local.origin.z + 5};minecraft:air",

    "${local.origin.x + 4};${local.origin.y - 2};${local.origin.z + 1};minecraft:air",
    "${local.origin.x + 4};${local.origin.y - 2};${local.origin.z + 2};minecraft:air",
    "${local.origin.x + 4};${local.origin.y - 2};${local.origin.z + 3};minecraft:air",
    "${local.origin.x + 4};${local.origin.y - 2};${local.origin.z + 4};minecraft:air",
    "${local.origin.x + 4};${local.origin.y - 2};${local.origin.z + 5};minecraft:air",

    # lava
    "${local.origin.x + 1};${local.origin.y - 3};${local.origin.z + 1};minecraft:lava",
    "${local.origin.x + 1};${local.origin.y - 3};${local.origin.z + 2};minecraft:lava",
    "${local.origin.x + 1};${local.origin.y - 3};${local.origin.z + 3};minecraft:lava",
    "${local.origin.x + 1};${local.origin.y - 3};${local.origin.z + 4};minecraft:lava",
    "${local.origin.x + 1};${local.origin.y - 3};${local.origin.z + 5};minecraft:lava",

    "${local.origin.x + 2};${local.origin.y - 3};${local.origin.z + 1};minecraft:lava",
    "${local.origin.x + 2};${local.origin.y - 3};${local.origin.z + 2};minecraft:lava",
    "${local.origin.x + 2};${local.origin.y - 3};${local.origin.z + 3};minecraft:lava",
    "${local.origin.x + 2};${local.origin.y - 3};${local.origin.z + 4};minecraft:lava",
    "${local.origin.x + 2};${local.origin.y - 3};${local.origin.z + 5};minecraft:lava",

    "${local.origin.x + 3};${local.origin.y - 3};${local.origin.z + 1};minecraft:lava",
    "${local.origin.x + 3};${local.origin.y - 3};${local.origin.z + 2};minecraft:lava",
    "${local.origin.x + 3};${local.origin.y - 3};${local.origin.z + 3};minecraft:lava",
    "${local.origin.x + 3};${local.origin.y - 3};${local.origin.z + 4};minecraft:lava",
    "${local.origin.x + 3};${local.origin.y - 3};${local.origin.z + 5};minecraft:lava",

    "${local.origin.x + 4};${local.origin.y - 3};${local.origin.z + 1};minecraft:lava",
    "${local.origin.x + 4};${local.origin.y - 3};${local.origin.z + 2};minecraft:lava",
    "${local.origin.x + 4};${local.origin.y - 3};${local.origin.z + 3};minecraft:lava",
    "${local.origin.x + 4};${local.origin.y - 3};${local.origin.z + 4};minecraft:lava",
    "${local.origin.x + 4};${local.origin.y - 3};${local.origin.z + 5};minecraft:lava",
  ]
}

resource "minecraft_block" "house" {
  for_each = toset(local.coordinates)
  material = split(";", each.value)[3]
  position = {
    x = tonumber(split(";", each.value)[0])
    y = tonumber(split(";", each.value)[1])
    z = tonumber(split(";", each.value)[2])
  }
}
